### ISSUE TITLE
[W4-geospatial-data-project] Luis Sanchez de Leon

### ISSUE THREAD

**Issue by lsdl13** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#11]
https://github.com/lsdl13/Proyecto-week4.git

**Comment by AnaAGG** [comment]
# 🗺🗺 W4-geospatial-data-project Luis 🗺🗺

Holaaaaa Luis 🙋‍♀️. Vamos a por el proyecto de este finde! 🔥🔥

## Readme

El readme esta perfecto 🎉🎉. Enhorabuena, esta super bien documentado, con cada uno de los pasos que seguiste y de una forma clara y concisa!

Solo por ponerme un poco tiquismiquis: 
- Cuando pones las librarias que usaste no hace falta que pongas `import json`, con que pongas `json` es suficiente. 
- Te quedaría perfecto si cuando nombras las librería que usaste pones el link a la documentación ofical de cada una. 

## Estructura del repositorio

También super bien Luis 🚀🚀🚀. 
- No dejaste los tokens a la vista 🔝
- Los jupyter numerados para saber cual es el orden de trabajo. 
- Cada uno de los jupyters super bien documentados en celdas de markdown 🔥
- Un par de detalitos:
    - Te dejaste fuera del `.gitignore` un archivo temporal `DS_Store`. 
    - Mezclas el español y el inglés, lo ideal, todo en un idioma. 
    - Meter el docstring en las funciones. Te dejo por aquí algo de [documentación](https://www.python.org/dev/peps/pep-0257/) por si te aporta valor. 

## Sintaxis de código

Vamos con la parte de la sintaxis de código:
- En el primer jupyter cuando ya tienes tu dataframe_final con todas empresas de las ciudades que has elegido, haces un drop para eliminar aquellas empresas que tienen menos de 10 empleados:
    ```python
    df_final.drop(df_final[df_final.number_of_employees < 10].index, inplace=True)
    ```
    Esta condición la puedes meter en tu query inicial y puedes quitar esta parte. 

- En el segundo jupyter, cuando haces esto: 
    ```python
    sr.geocode("barcelona")
    barna={'type': 'Point', 'coordinates': [2.15379, 41.40359]}
    ```
    Puedes simplicarlo asignando directamente una variable a la llamada de la función
    ```python
    barna = sr.geocode("barcelona")
    ```
- En el segundo jupyter se podría atomizar el código para no tener que ejecutar el mismo código para cada una de las parametros de foursquare. 
    - Te puedes crear una lista con los parámetros que has considerado importantes:
    ```python
    query = ["Vegan", "Starbucks", "Basketball Stadium", "Preschool"]
    ```
    - Una vez que tienes esta lista puedes iterar por ella llamando a la función `data` 
    ```python
    for i in query:
        barcelona = data(lat, long, i)
        # de esta forma se te almacenarán todos los resultados de las queries para barcelona en la variable barcelona. 
    ```
    - Por último haces el dataframe con la función que te creaste. 
- En la parte de visualización sacaste mapas y gráficas suuper bien, 
## ToDo
- Las geoqueries, puedes usar [near](https://docs.mongodb.com/manual/reference/operator/query/near/) o  [geonear](https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/).

- Te dejo por aquí algunos *tips* para las geoqueries, pero si quieres lo vemos luego: 
    - Lo primero que tienes que hacer es meter en un colección de mongo los resultados de foursquare
    - Para poder hacer geoqueries, las coordenadas tienen que estar en `2dsphere` (esto lo podemos hacer en mongo)
    - Empezamos con las queries:
    ```python
    query = {"location": {"$near": {"$geometry": LAS COORDENAS DE BARCELONA, PARIS O MUNICH,"$minDistance": 500  , "$maxDistance": 1000}}} # con esto lo que haremos será sacar todos los Starbucks , veganos, estadios de baloncesto o escuelas que esten entre 500 y 1000 metros de cada una de las coordenadas que le pasemos.

    barcelona = db.find(query) 
    df = pd.DataFrame(list(barcelona)) # lo pasamos a un dataframe, con el que luego podremos hacer los mapas y gráficas que tienes. 
    ```

- Me ha faltado el *story telling* o la interpretación de las gráficas. Esta todo genial, pero al final ¿En qué ciudad pongo mi empresa?

Bueno Luis, has hecho muy buen trabajo en este proyecto. Se nota que has disfrutado con este proyecto!! Si te quedó alguna duda con alguna corrección pregúntanos!
