### ISSUE TITLE
[W4-geospatial-data-project]Javier Cabrera

### ISSUE THREAD

**Issue by Javi-Python** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#13]
https://github.com/javielpapi/GEOspatial-BusinessGuy

La verdad no me dio tiempo a acabarlo por muchos problemas tecnicos, voy a intentar de hacerle unos edits esta semana y tenerlo completamente acabado, lo siento.

**Comment by breogann** [comment]
Hola Javi! 🙋🏻‍♂️

Te voy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: se te ha colado un .DS_Store 🔪 Para eliminar estos arhicvos, primero tienes que decirle a git que los destrack-ee con ``git rm --cached el archivo`` . Luego borrar el archivo, incluirlo en el gitijgnore  y hacer git add, commit y push de nuevo.
    - No lo llames *jasons* pls 🥲
    - Si puedes, numera los jupyters

- El **[README.md](http://readme.md) ✍🏻**: lo veo bien. Has explicado los objetivos y las librerías. Puedes también incluir los criterios y procedimientos que has seguido.

- Respecto al código:
    - En api_calls.py:
        - Genial por poner los docstrings. Recuerda que tienes que pone varias cosas: una definición sencilla de lo que hace la función junto con los argumentos que recibe y el tipo que son.
        - Esto:

            ```python
            client = MongoClient('localhost:27017')
            ```

            lo puedes dejar hecho una sola vez fuera de la función, para no tener que definirlo cada vez. 

        - Por lo demás, lo veo bien 👌
    - Para los jupyter:
        - Geo-Project.ipynb:
            - Deja las importaciones siempre al principio
        - API CALLS W FUNCTIONS.ipynb
            - Limita los prints ⚠️ es casi imposible encontrar el código: [https://github.com/Javi-Python/GEOspatial-BusinessGuy/blob/main/API CALLS W FUNCTIONS.ipynb](https://github.com/Javi-Python/GEOspatial-BusinessGuy/blob/main/API%20CALLS%20W%20FUNCTIONS.ipynb)
            - Parece que las funciones están bien parametrizadas 👏
        - Finding Out What is Near.ipynb
            - Esto lo puedes refactorizar:

                ```python
                near_paypal_filtered = near_paypaldf[near_paypaldf['duplicated'] == False]
                near_google_filtered = near_googledf[near_googledf['duplicated'] == False]
                near_yahoo_filtered = near_yahoodf[near_yahoodf['duplicated'] == False]
                near_vmwared_filtered = near_vmwaredf[near_vmwaredf['duplicated'] == False]
                near_twitter_filtered = near_twitterdf[near_twitterdf['duplicated'] == False]
                ```

                con un bucle y un format.

    Al final no te dio tiempo a incluirlo en la base de datos, ¿no? ¿qué problemas técnicos tuviste Javi?

    Sí que le puedes incluir más cosas, pero el código que tienes lo veo bastante bien. 

    A tope con el siguiente!! 💪
