### ISSUE TITLE
[W4-geospatial-data-project] Alberto Pérez

### ISSUE THREAD

**Issue by asiokfd** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#14]

**Comment by asiokfd** [comment]
https://github.com/asiokfd/Proyecto3

**Comment by asiokfd** [comment]
Las funciones están sin referenciar, no me funcionaban, me daba problemas con las librerias, aún poniendo los imports dentro de la función, dentro del archivo de funciones... en todos lados

**Comment by breogann** [comment]
Hola Alberto! 🙋🏻‍♂️

Te voy comentando, averquénossale:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: está genial, no te se ha colado ningún archivo temporal.
    - También tienes yml y el requirements.txt
    - El jupyter no hace falta que vaya dentro de la carpeta de src. Al final src es el sitio donde guardamos el código para utilizarlo en otros sitios: o bien un [main.py](http://main.py) que sea ejecutable o bien jupyters donde haces otras cosas.

- El **[README.md](http://readme.md) ✍🏻**:
    - Lo veo muy bien. Echo en falta quizá una captura del mapa. Veo que lo tienes exportado en html, pero puedes incluir alguna imagen. También puedes incluir los criterios por los que te has guiado.

- Respecto al código 👩‍💻:
    - En el **src**: nada que decirte.
    - En los **jupyters**:
        - El JSON_normalize aplana un json y lo convierte a dataframe. Te dejo este enlace, que lo explica mucho mejor que yo: [https://towardsdatascience.com/all-pandas-json-normalize-you-should-know-for-flattening-json-13eae1dfb7dd](https://towardsdatascience.com/all-pandas-json-normalize-you-should-know-for-flattening-json-13eae1dfb7dd)

             sería así:

            ```python
            data = [{'id': 1, 'name': {'first': 'Coleen', 'last': 'Volk'}},
                     {'name': {'given': 'Mose', 'family': 'Regner'}},
                     {'id': 2, 'name': 'Faye Raker'}]
            pd.json_normalize(data)
            ```

        - Para estas funciones:

            ```python
            starsfan=gmaps.places_nearby(
                
                location = sfan["coordinates"],
                radius = 200,
                name = "Starbucks"
                
            )
            ```

            has hecho tres párrafos de código iguales. Lo único que te cambia es el Starbucks y la ciudad. Eso lo puedes meter en una función y parametrizar para que te reciba esos dos argumentos y ejecutar la función tres veces.

        - Una vez que tengas tu código en [archivos.py](http://archivos.py), tienes que importarlo en jupyter, por lo que sustituyes las funciones que tengas definidas dentro del notebook por las que has importado. Vamos, que no tienes que tener funciones definidas en el notebook si ya las importas desde otro sitio.
        - Para esta función:

            ```python
            dfpuntuacion["Ubicacion"]= ["San_Francisco", "Brooklyn", "London"]
            dfpuntuacion["Densidad_Starbucks_200mtr"]= [len (starsfan["results"]),len (starsbkyn["results"]),len (starslond["results"])] 
            dfpuntuacion["Densidad_Bares_1000mtrs"]= [len (partysfan["results"]),len (partybkyn["results"]),len (partylond["results"])] 
            dfpuntuacion["Densidad_Veganos_1000mtrs"]= [len (veganssfan["results"]),len (vegansbkyn["results"]),len (veganslond["results"])] 
            dfpuntuacion["Densidad_Colegios_1500mtrs"]= [len (nenesfan["results"]),len (nenesbkyn["results"]),len (neneslond["results"])] 
            dfpuntuacion["Radio_para_encontrar_10_coles"]= [radio_nenes_sfan, radio_nenes_bkyn, radio_nenes_lond]
            ```

            intenta refactorizarlo 🙏; con un bucle podrías hacerlo.

        - Cuando dices "# no lo he hecho función porque el key "Category" lo voy a rellenar a mano":

            ```python
            dicparty = []
            for dic in decodeparty2lond:
                paralista = {}
                paralista["Name"] = getFromDict(dic, mapa_nombre)
                paralista["latitud"]= getFromDict(dic, mapa_latitud)
                paralista["longitud"] = getFromDict(dic,mapa_longitud)
                paralista["Rating"] = getFromDict (dic, mapa_rating)
                paralista["Category"]= "Bares_pubs"
                dicparty.append(paralista)
            ```

            puedes hacerlo función y eso que pasas a mano sería con lo que llamarías a la función, ¿no? (o no te he entendido?)

        - Recuerda limitar los outputs: tanto de los jsons como de los
        - Está súper bien que hayas ido poniendo títulos y aclaraciones en el código.

    Si te he seguido bien el hilo (aprovecha  y numera los títulos de los pasos grandes que vayas haciendo), has:

    1. Filtrado la base de datos de mongo
    2. Con eso te has quedado con tres ciudades
    3. Has hecho queries (colegios, veganos y fiestas) a tres ciudades (Londres, San Francisco y Brooklyn)
        1. Como no te devolvían muchos colegios, has optado por utilizar el número de colegios en vez del radio.
    4. Con esto, has elegido la ciudad. Una vez con la ciudad (Londres) y encontrar el resto de criterios cerca de esa oficina (porque al elegir ciudad sólo tenías una que cumplía esos requisitos)
        - ¿Puede ser que sólo te devolviera tres empresas por filtrar por la M pero hubiera cantidades en números que fueran más de un millón?

    Si no es así, corrígeme porfa.

En general, tienes mucho código que se repite y que se puede modularizar para no repetirlo. Te recomendaría también:

- Que partieras los jupyters en vez de tener todo en el mismo: quizá uno por cada paso "grande". También, además de exportar el mapa, exporta el dataframe final (yo puedo ejecutar tu código pero puedo no tener el token de google. Entonces si abro un jupyter que importa ese df y lo ejecuto, puedo visualizar el mapa. Aunque sí, también lo puedo abrir desde el html). Por ejemplo, un jupyter para mongoqueries, otro para API's y otro para visualización.
- Que modularices funciones y no tengas código repetido; aprovechando el código de src
- Me habría gustado también alguna **geoquery de mongo**. Al final las queries a mongo las has utilizado sólo para un filtrado inicial. 
- Que los datos que consigues, además de tenerlos exportados o no, que lo tengas en mongo. Puedes crear una colección nueva con los datos que has extraído.
- Y bueno, es un proyecto de geolocalización, así que aprovecha y utiliza imágenes! (alguna captura de kepler en el readme)

PD: Acabo de re-leer esto que me ponías: "Las funciones están sin referenciar, no me funcionaban, me daba problemas con las librerias, aún poniendo los imports dentro de la función, dentro del archivo de funciones... en todos lados". No acabo de entender a qué te refieres. ¿no se te importaban en jupyter y por eso las tienes definidas dentro del notebook?

Te pongo estas cosas para mejorar porque somos muy pesados, pero veo que le has echado trabajo; y has cumplido con lo que se te pedía, que era tomar decisiones basadas en datos 💪
