### ISSUE TITLE
[W4-geospatial-data-project] Pablo Fernández Cañete

### ISSUE THREAD

**Issue by pfernancanete** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#16]
En vez de ir seleccionando por empresas he escogido una a mi elección, viendo si cumple los requirements de los empleados. Viendo que me cumple los requisitos me he quedado con ella

**Comment by pfernancanete** [comment]
https://github.com/pfernancanete/W4-geospatial-data-project

**Comment by breogann** [comment]
Hola Pablo! 🙋🏻‍♂️

Te voy comentando:

Lo primero: has utilizado un planteamiento inductivo o retraoctivo. Te has ido a lo concreto y desde ahí has confirmado que era una opción correcta. Esto es muy arriesgado porque ¿cuál es el criterio de corte para ver que esa ubicación está bien? ej.: siempre te va a devolver Starbucks, más o menos cerca. 

También, si esa empresa resulta que no cumple con los criterios que has puesto, ¿repites el mismo proceso con otra? ¿y si esa otra tampoco lo cumple? 

Lo segundo que veo, antes de entrar a ver los archivos, es que no tienes ninguna carpeta. El código fuente, por convención, va en la carpeta src. Y también, por convención, no se recomienda llamar "funciones" a tu archivo de funciones. Tienen que tener siempre nombres significativos. 

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no se te ha colado ningún archivo temporal.
    - Numera los jupyter, para que sigan un orden lógico: primero el filtro, luego la api, luego los mapas, etc.
    - Como te decía, tendrías que tener una carpeta de src con los archivos de funciones nombrados de forma significativa.

- El **[README.md](http://readme.md) ✍🏻**: lo veo bastante bien. Has explicado el objetivo y los criterios. También has incluido una captura del resultado. Si quisieras, podrías también incluir librerías

- Respecto al código:
    - En funciones.py
        - Has copiadp y pegado la función y no la tienes indentada
        - Esto:

            ```python
            donde = input
            ```

            sin poner los paréntesis, ¿te funciona?

    - Para los jupyter:
        - API calling.ipynb
            - No dejes los jupyters impresos con errores.
            - Pon todas las importaciones al principio del jupyter
        - Map.ipynb:
            - Esto:

            ```python
            #0. Oficina:

            of_lat = 40.726155
            of_lon = -73.995625
            ```

            lo puedes poner en un diccionario:

            ```python
            ubicaciones = {"oficina": [40.726155,
            -73.995625]
            }
            ```

            y así sólo tendrías una variable, en vez de 10 (lotitud y longitud por cada cosa que quieres buscar).

        - El mapa aprovecha para exportarlo

    Lo que echo un poco en falta (que es cierto que no era obligatorio) es el que una vez hechas las llamadas, las guardes en mongo para hacer **geoqueries**. 

    Es importante que:

    - Hagas el archivo de funciones y guardes ahí el código
    - Que luego lo importes en el jupuyter
    - Cambies un poco la estructura del repo
    - Que tengas en cuenta que un planteamiento inductivo no es lo mejor para este tipo de problemas

    El manejo de los dataframes y las coordenadas está muy bien.  Has hecho mongoqueries y has hecho llamadas a API's. Los jupyters están bien comentados y has hecho visualización.

    Para el próximo proyecto ten en cuenta estos tips! 

    A tope con el siguiente 💪
