### ISSUE TITLE
[W4-geospatial-data-project] Edu Martinez

### ISSUE THREAD

**Issue by EduMartinezGarrido** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#19]
https://github.com/EduMartinezGarrido/Geospatial_data_project

**Comment by breogann** [comment]
Hola Edu! 🙋🏻‍♂️

Te voy comentando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no tienes gitignore 🔪. Necesitas tenerlo. De hecho, se te ha colado un arhcivo temporal que es el DS_Store. En tu repo sólo tienes que tener lo que te aporta valor. Para borrarlo, tendrás que hacer:

        ```python
        git rm --cached .DS_Store
        ```

        y luego meterlo en el .gitignore y repetir el proceso de git add, commit y push. Te pasa lo mismo con __pycache __. 

    - Numera los jupyter, para que sigan un orden lógico: primero el filtro, luego la api, luego los mapas, etc.
    - Los mapas los metería en una carpeta de mapas o en la de output.

- El **[README.md](http://readme.md) ✍🏻**:
    - Está súper bien. Explicas tu objetivo, los medios que utilizas, las librerías.
    - Podrías incluir si quieres:
        - alguna caputra del mapa
        - las opciones que tenías (ciudades), la opción elegida, etc.
        - Los criterios que has utilizado para guiar tu proyecto
    - Para las librerías, no hace falta que las pongas como extracto de código de los import. Sólo con el nombre (y el enlace) es suficiente.
- Respecto al código:
    - En el src (funcionasAPI.py):
        - Te faltan los docstrings 🔪. Documenta el código como te gustaría encontrártelo. ¿Recuerdas cómo fue navegar por las documentaciones de las API's?     Better explicit than implicit. ([https://www.python.org/dev/peps/pep-0020/](https://www.python.org/dev/peps/pep-0020/))
        - Esta función:

            ```python
            def puntuacion(df_concat):
                df_concat.loc[df_concat.bar < 45, "bar"]= 2
                df_concat.loc[df_concat.bar > 45, "bar"]= 3
                df_concat.loc[df_concat.Starbucks == 50, "Starbucks"]= 1
                df_concat.loc[df_concat.Starbucks == 51, "Starbucks"]= 2
                df_concat.loc[df_concat.Starbucks > 51, "Starbucks"]= 3
                df_concat.loc[df_concat.basket < 30, "basket"]= 1
                df_concat.loc[df_concat.basket == 36, "basket"]= 2
                df_concat.loc[df_concat.basket >36, "basket"]= 3
                df_concat.loc[df_concat.nursery < 10, "nursery"]= 1
                df_concat.loc[df_concat.nursery == 18, "nursery"]= 3
                df_concat.loc[df_concat.nursery > 10, "nursery"]= 2
                df_concat.loc[df_concat.taxi < 3, "taxi"]= 1
                df_concat.loc[df_concat.taxi == 3, "taxi"]= 2
                df_concat.loc[df_concat.taxi > 3, "taxi"]= 3
                df_concat.loc[df_concat.vegan < 10, "vegan"]= 1
                df_concat.loc[df_concat.vegan > 30, "vegan"]= 3
                df_concat.loc[df_concat.vegan > 10, "vegan"]= 2
                return df_concat
            ```

            está pidiendo a gritos una refactorización. Lo que decimos siempre: si hay líneas de código muy parecidas y muy repetidas, probablemente se pueda refactorizar. ¿cómo? probablemente lo más fácil sea utilizar un diccionario sobre el que iterar. 

    - Para los jupyter:
        - API-FourSquare.ipynb
            - Empiezas a hacer queries con una localización, ¿aleatoria? entiendo que será la ubicación que te devuelva google cuando pones San Francisco, pero tienes librerías con las que puedes obtener esa información sin tener que hacerlo a mano.
            - Aquí lo mismo:

                ```python
                los_angeles_vegan = fa.get_data(34.085749, -118.343791,url_query,*queries_vegan)

                los_angeles_nursery = fa.get_data(34.085749, -118.343791,url_query,*queries_nursery)

                los_angeles_bar = fa.get_data(34.085749, -118.343791,url_query,*queries_bar)

                los_angeles_taxi = fa.get_data(34.085749, -118.343791,url_query,*queries_taxi)

                los_angeles_basket = fa.get_data(34.085749, -118.343791,url_query,*queries_basket)

                los_angeles_starbucks = fa.get_data(34.085749, -118.343791,url_query,*queries_starbucks)
                ```

                Si tienes una función donde lo único que cambia son las ciudades y las ubicaciones pero la función hace lo mismo para todas: ahí tienes tus dos parámetros. 

            - Está genial que te hayas importado las funciones desde src.
        - Mongo_companies_filter.ipynb:
            - Vale, ahora veo la de dónde has sacado la ubicación! Tienes los jupyters nombrados (fallo mío) pero no los tienes numerados
        - Kepler.ipynb
            - El mapa no es obligatorio, pero si quisieras tenerlo más completo, aprovecha para poner etiquetas en los puntos. ¿Qué color significa cada punto? ¿son empresas? ¿son Starbucks?
            - También aprovecha que tienes la visualización hecha e incluye una captura en el readme. Por ejemplo, yo he tenido que clonarme el repo para poder abrir el archivo de html.

    En términos generales, te diría:

    - Refactoriza funciones y parametriza para evitar repetir código
    - Incluye los docstrings
    - Lo óptimo e ideal sería que esa info que recibes de las llamadas a la API puedas meterlo en mongo en una nueva colección y entonces hacer g**eoqueries a mongo.**
    - Has hecho visualización, pero echo un falta un stopry-telling o una conclusión explícita de la decisión que has tomado

    El proyecto está bien, has hecho mongoqueries, has hecho llamadas a API's y tienes el código modularizado e importado en notebooks. También has hecho visualización y has ponderado. La organización del repo también está bien.

    Sólo las cosas que te cuento un poco más arriba. Cualquier cosa me dices. 

    Seguimos Edu!! 💪
