### ISSUE TITLE
[W4-geospatial-data-project] Fran

### ISSUE THREAD

**Issue by FranLeston** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#3]
[W4 project](https://github.com/FranLeston/W4-geospatial-data-project)

**Comment by breogann** [comment]
Hola Fran! 🙋🏻‍♂️

Te voy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: perfect, no se te ha colado ningún archivo temporal.
    - El resto: la numeración de los jupyter, la carpeta src  y la carpeta de data, está todo 👌

- El **[README.md](http://readme.md) ✍🏻**: has dejado el nuestro 🔪🔪🔪

- Respecto al código:
    - En src:
        - Te faltan los docstrings!
    - Para los jupyter:
        - El jupyter en github no se renderiza, pero en nbviewer no hay problema: [https://nbviewer.jupyter.org/github/FranLeston/W4-geospatial-data-project/blob/master/01-dbquery.ipynb](https://nbviewer.jupyter.org/github/FranLeston/W4-geospatial-data-project/blob/master/01-dbquery.ipynb) puedes aprovechar y ponerlo en el readme.
        - Lo único es intentar refactorizar los párrafos de código para plotear los mapas.

Has elegido la ciudad, pero dentro de la ciudad, ¿has elegido algún punto concreto? También puedes aprovechar y guardar los datos en mongo para luego poder hacer **geoqueries**

El proyecto está bien, has cumplido con los objetivos y lo que tienes está bien, pero sé que puedes hacer mucho más Fran!!
