### ISSUE TITLE
[W4-geospatial-data-project] Julieta Strayfurman

### ISSUE THREAD

**Issue by julistary** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#4]
https://github.com/julistary/GeoSpatial_Data_Project.git

**Comment by breogann** [comment]
Hola Julieta! 🙋🏻‍♂️

Te voy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: has utilizado la plantilla de github y has incluido otros archivos nuevos.
    - Has nombrado los archivos de la carpeta src de forma significativa 👌
    - Tienes un [config.py](http://config.py) vacío en la root?
    - Por lo demás, la organización la veo per-fecta.

- El **[README.md](http://readme.md) ✍🏻**: está genial. Explicas el objetivo del proyecto, los medios, las librerías y el procedimiento. Nada que decir.

    Bueno, sí, aprovecha que es un proyecto muy visual y añade una captura del mapa en el README si quieres.

- Respecto al código:
    - En src:

        Los docstrings están súuuper bien: explicas lo que hacen, los argumentos que reciben y devuelven y el tipo.

        - cities_coordinates.py
            - ¿Has hecho una función para cada ciudad? 🔪 o sea, entiendo que has querido encapsular el código, pero igual puedes hacer una con geopy para hacerlo más sencillo.
        - geoqueries.py
            - Aquí:

                ```python
                def grades(x):
                    if x == 0:
                        return 0
                    elif (x > 0) and (x <= 8):
                        return 1
                    elif (x > 8) and (x <= 20):
                        return 2
                    else:
                        return 3
                ```

                igual puedes utilizar un diccionario, si te resulta más cómodo.

                Y aqui:

                ```python
                for l in list_:
                            if l['place'] == 'party':
                                party += 1
                            elif l['place'] == 'starbucks':
                                starbucks += 1
                            elif l['place'] == 'school':
                                school += 1
                            elif l['place'] == 'vegan':
                                vegan += 1
                            elif l['place'] == 'basket':
                                basket += 1
                ```

                puedes iterar sobre l in list_ y también sobre party, starbucks, etc. Así sólo te haces un bucle doble con una sola condición. 

    - Para los jupyter:
        - 1.selecting_cities.ipynb
            - Has utilizado un montón de regex 👏
            - Has importado las funciones que has hecho en otro sitio en el notebook y tienes el código justo.
        - Los jupyters están muy organizados
        - El story telling también está muy bien hecho: sencillo, sintético y con la información que necesitas. Lo único es que las imágenes no se renderizan (tampoco en nbviewer).
        - Eres de las pocas personas (que yo he corregido) que ha explicitado las coordenadas finales como resultado final 👏

    No te puedo decir mucho más del código. El proyecto está genial Julieta. Tanto por forma como por contenido como planteamiento (incluso con los requirements y el yml). De pasos extra, si quisieras hacer, sería:

    - Incluir esos datos en mongo
    - Hacer geoqueries a mongo para luego hacer todo el proceso de ponderación

    Pero vamos, que enhorabuena por el trabajo!! Vas en cohete!! 🚀
