### ISSUE TITLE
[ W4-geospatial-data-project] Alberto Pérez-Lescure

### ISSUE THREAD

**Issue by Albertoplm** [Ironhack-Data-Madrid-Marzo-2021/W4-geospatial-data-project#7]
[Link to my repo](https://github.com/Albertoplm/geospatial-data-project.git)

https://github.com/Albertoplm/geospatial-data-project.git

**Comment by breogann** [comment]
Hola Alberto! 🙋🏻‍♂️

Te voy contando:

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no se te ha colado ningún archivo temporal.
    - Si puedes, numera los jupyters; que siempe ayuda que la persona que entre a tu repo lo entienda mejor

- El **[README.md](http://readme.md) ✍🏻**: Has pasado directamente a los requisitos sin introducir el objetivo. Respecto al planteamiento, has elegido Madrid y entonces has lanzado queries que confirmen, ¿no? pero es un proceso inductivo/retroactivo. ¿Qué pasa si no no te cuadra, eliges otra ciudad al azar y repites el proceso?  Por esto decíamos que intentarais tomar las decisiones basadas en datos. Es cierto que para este proyecto es algo difícil enfocarlo y basarlo tooodo en datos, pero intenta evitar lo arbitrario.
    - Utilizas una foto de portada de Berlín. Si no lo utilizas en el proyecto, yo la qiutaría para no llevar a confusión.

- Respecto al código:
    - En api.py:
        - Te faltan las docstrings
        - Esto se puede refactorizar:

            ```python
            for i, row in df.iterrows():
                    if row["tipo"] == "vegan":
                        vegan.append(row.dist)
                    elif row["tipo"] == 'club':
                        club.append(row.dist)
                    elif row["tipo"] == 'competency':
                        competency.append(row.dist)
                    elif row["tipo"] == 'kindergarten':
                        kindergarten.append(row.dist)
                    elif row["tipo"] == 'starbucks':
                        starbucks.append(row.dist)
                    elif row["tipo"] == 'basketball':
                        basketball.append(row.dist)
                    elif row["tipo"] == 'hairdresser':
                        hairdresser.append(row.dist)
            ```

            si creas una lista con vegan, club, etc y apendizas a una lista con un format. 

    - Está genial que hayas utilizado geoqueries (podías haber utilizado sólo pandas)
    - También la función de cálculo de distancias
    - El jupyter no se renderiza en github, pero sí en nbviewer: [https://nbviewer.jupyter.org/github/Albertoplm/geospatial-data-project/blob/main/maps.ipynb](https://nbviewer.jupyter.org/github/Albertoplm/geospatial-data-project/blob/main/maps.ipynb), aprovecha y ponlo en el readme si quieres
    - El resto de código está bien. Simplemente la parte del planteamiento, que sé que era difícil de abordar, pero tenlo en cuenta de cara al futuro. 

Buen trabajo, a tope con el siguiente Alberto!! 💪
